### ISSUE TITLE
How to Implement this for iDempere ver 11 ?

### ISSUE THREAD

**Issue by VianDriYanto** [HideakiHagiwara/jpiere.modifications#1]
Hay Hideaki, 

When i'm trying to install this on the my windows 11. I can not maven verify this Plugin. I Put the plugin outside the folder of iDempiere. Like this
iDProject
   -- idempiere
   -- jpms
when im trying to mvn verify inside folder jpms is not working, eventhough im already change the Manifest in org.adempiere.base and zk. 

Regadrs
Avian

**Comment by JPiere** [comment]
This is not JPMS Issue.
Please see wiki : https://wiki.idempiere.org/en/JPiere_Development_environment_establishment
